# Generated by Django 5.1.7 on 2025-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='user_uid',
            field=models.CharField(default='Khushi', max_length=128),
            preserve_default=False,
        ),
    ]
