# Generated by Django 5.1.7 on 2025-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_remove_uploadeddocument_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='user_uid',
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='user_name',
            field=models.CharField(default='Anonymous User', max_length=128),
        ),
    ]
