# Generated by Django 5.1.7 on 2025-04-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_remove_uploadeddocument_user_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddocument',
            old_name='encrypted_summary',
            new_name='encrypted_cleaned',
        ),
    ]
