# Generated by Django 5.1.7 on 2025-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_rename_encrypted_summary_uploadeddocument_encrypted_cleaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='summary',
            field=models.TextField(default='Hello'),
        ),
    ]
