# Generated by Django 5.1.7 on 2025-04-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_uploadeddocument_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='decrypted_preview',
        ),
    ]
